server:
  port: 8080

spring:
  application:
    name: hello-rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    stream:
      username: guest
      password: guest
#    listener:
#      simple:
#        retry:
#          enabled: true # 재시도 활성화
#          initial-interval: 1000ms # 첫 재시도 대기 시간 1초
#          max-attempts: 3 # 최대 재시도 횟수
#          max-interval: 1000ms # 시도간 최대 대기시간(기본:10초)
#        default-requeue-rejected: false # 재시도 실패 시 자동으로 DLQ로 이동
