server:
  port: 8080

spring:
  application:
    name: hello-rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    stream:
      username: guest
      password: guest
  profiles:
    include:
      - 'step8_2'